[Python Numpy – Introduction to ndarray [Part 1]](https://www.machinelearningplus.com/python/numpy-tutorial-part1-array-python-examples/)

# Training

## Introduction to Numpy
Numpy is the most basic and a powerful package for working with data in python.

If you are going to work on data analysis or machine learning projects, then having a solid understanding of numpy is nearly mandatory.

Because other packages for data analysis (like pandas) is built on top of numpy and the scikit-learn package which is used to build machine learning applications works heavily with numpy as well.

So what does numpy provide?

At the core, numpy provides the excellent ndarray objects, short for n-dimensional arrays.

In a ‘ndarray’ object, aka ‘array’, you can store multiple items of the same data type. It is the facilities around the array object that makes numpy so convenient for performing math and data manipulations.

You might wonder, ‘I can store numbers and other objects in a python list itself and do all sorts of computations and manipulations through list comprehensions, for-loops etc. What do I need a numpy array for?’

Well, there are very significant advantages of using numpy arrays overs lists.

To understand this, let’s first see how to create a numpy array.

In [97]:
import numpy as np

## How to Create a List ?

In [98]:
# Create list
list1 = [0,1,2,3,4]
print(type(list1))
list1

<class 'list'>


[0, 1, 2, 3, 4]

## How to Create an Array ?

In [99]:
# Create an 1d from a list
array1d = np.array(list1)
print(type(array1d))
array1d

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4])

## Whats the difference between an array and list ?

The key difference between an array and a list is, arrays are designed to handle vectorized operations while a python list is not.

That means, if you apply a function it is performed on every item in the array, rather than on the whole array object.

Let’s suppose you want to add the number 2 to every item in the list. The intuitive way to do it is something like this:

### Add +2 to every number in the Array

In [100]:
# Add +2 to every number in the Array
array1d + 2

array([2, 3, 4, 5, 6])

#### Create Array 2d

In [101]:
# Create a 2d List
list2 = [[0,1,2],[3,4,5],[6,7,8]]
print(type(list2))
list2

<class 'list'>


[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [102]:
# Create a 2d Array from a list of lists
array2d = np.array(list2)
print(type(array2d))
array2d

<class 'numpy.ndarray'>


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Manipulate Array DataType : 'float', 'int', 'bool', 'str' and 'object'


##### float

In [103]:
array2d_float = np.array(list2,dtype='float')
array2d_float

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

##### int

In [104]:
array2d_float = np.array(list2,dtype='int')
array2d_float

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### bool

In [105]:
array2d_float = np.array(list2,dtype='bool')
array2d_float

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

##### str

In [106]:
array2d_float = np.array(list2,dtype='str')
array2d_float

array([['0', '1', '2'],
       ['3', '4', '5'],
       ['6', '7', '8']], dtype='<U1')

##### object

In [107]:
array2d_float = np.array(list2,dtype='object')
array2d_float

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=object)

#### Return Array to a List

In [108]:
array2d.tolist()

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

## How to inspect the size and shape of a numpy array?


1.   If it is a 1D or a 2D array or more. (use ndim)
2.   How many items are present in each dimension (use shape)
3.   What is its datatype (use dtype)
4.   What is the total number of items in it (use size)
5.   Samples of first few items in the array (through indexing)




    
    
    
    
    

In [109]:
#create 2d array with 3 rows and 4 columns
list3 = [[1,2,3,4],[3,4,5,6],[5,6,7,8]]
array3d = np.array(list3, dtype='float')
array3d

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [110]:
#shape
print('shape (columns,rows): ', array3d.shape)
#dtype
print('datetype:', array3d.dtype)
#size
print('size: ', array3d.size)
#dimensions
print('num dimensions:', array3d.ndim)

shape (columns,rows):  (3, 4)
datetype: float64
size:  12
num dimensions: 2


### Extract Elements from Array

In [111]:
#Extract the first 2 rows and columns
array3d[:2, :2]

array([[1., 2.],
       [3., 4.]])

### Boolean Array

A boolean index array is of the same shape as the array-to-be-filtered and it contains only True and False values. The values corresponding to True positions are retained in the output.

In [112]:
b = array3d > 4
b

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [113]:
array3d[b]

array([5., 6., 5., 6., 7., 8.])

## Reverse Rows and The Whole Array

#### Reverse only the row positions

In [114]:
array3d[::-1,]

array([[5., 6., 7., 8.],
       [3., 4., 5., 6.],
       [1., 2., 3., 4.]])

#### Reverse the row and column positions

In [115]:
array3d[::-1, ::-1]

array([[8., 7., 6., 5.],
       [6., 5., 4., 3.],
       [4., 3., 2., 1.]])

## How to represent missing values and infinite

In [116]:
# Insert a nan and an inf
array3d[1,1] = np.nan #not a number
array3d[1,2] = np.inf #infinite
array3d

array([[ 1.,  2.,  3.,  4.],
       [ 3., nan, inf,  6.],
       [ 5.,  6.,  7.,  8.]])

In [117]:
# Replace nan and inf with -1
missing_bol  = np.isnan(array3d) | np.isinf(array3d)
array3d[missing_bol] = -1
array3d

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

## How to compute mean, min, max on the ndarray

##### mean, min and max

In [118]:
# mean, max and min
print('mean value is: ', array3d.mean())
print('min value is: ', array3d.min())
print('max value is: ', array3d.max())

mean value is:  3.5833333333333335
min value is:  -1.0
max value is:  8.0


##### row wise and column wise min

In [119]:
print('column wise min: ', np.amin(array3d, axis=0))
print('row wise min: ', np.amin(array3d, axis=1))

column wise min:  [ 1. -1. -1.  4.]
row wise min:  [ 1. -1.  5.]


##### row wise and column wise max

In [120]:
print('column wise min: ', np.amax(array3d, axis=0))
print('row wise min: ', np.amax(array3d, axis=1))

column wise min:  [5. 6. 7. 8.]
row wise min:  [4. 6. 8.]


##### cumulative sum

In [121]:
np.cumsum(array3d)

array([ 1.,  3.,  6., 10., 13., 12., 11., 17., 22., 28., 35., 43.])

## How to create a new array from an existing array

If you just assign a portion of an array to another array, the new array you just created actually refers to the parent array in memory.

That means, if you make any changes to the new array, it will reflect in the parent array as well.

So to avoid disturbing the parent array, you need to make a copy of it using copy(). All numpy arrays come with the copy() method.


In [122]:
array2dA = array2d[:2,:2]
array2dA

array([[0, 1],
       [3, 4]])

In [123]:
# assign portion of array2d to array2dA. doenst really create a new array
array2dA[:1,:1] = 100 
array2d

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [124]:
# copy portion of array2d to array2dB
array2dB = array2d[:2,:2].copy()
array2dB[:1,:1] = 101 #101 will not reflect in array2d
array2d

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

## Reshaping and Flattening Multidimensional arrays

Reshaping is changing the arrangement of items so that shape of the array changes while maintaining the same number of dimensions.

Flattening, however, will convert a multi-dimensional array to a flat 1d array. And not any other shape.

In [125]:
array3d

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [126]:
array3d.reshape(4,3)

array([[ 1.,  2.,  3.],
       [ 4.,  3., -1.],
       [-1.,  6.,  5.],
       [ 6.,  7.,  8.]])

## What is the difference between flatten() and ravel()

There are 2 popular ways to implement flattening. That is using the flatten() method and the other using the ravel() method.

The difference between ravel and flatten is, the new array created using ravel is actually a reference to the parent array. So, any changes to the new array will affect the parent as well. But is memory efficient since it does not create a copy.

In [127]:
array1d

array([0, 1, 2, 3, 4])

In [128]:
# flatten it to a 1d array

array1d.flatten()

array([0, 1, 2, 3, 4])

In [129]:
# changing the flattened array does not change parent

b1 = array1d.flatten()
b1[0] = 100
array1d

array([0, 1, 2, 3, 4])

In [130]:
# changing the raveled array changes the parent also

b2 = array1d.ravel()
b2[0] = 101
array1d

array([101,   1,   2,   3,   4])

## How to create sequences, repetitions and random numbers using numpy

#### function np.arange(x,n,asc)

In [131]:
#lower limit is 0 be default
print(np.arange(5))

[0 1 2 3 4]


In [132]:
#0 to 9
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [133]:
#0 to 9 with step of 2
print(np.arange(0,10,2))

[0 2 4 6 8]


In [134]:
# 10 to 1, decreasing order
print(np.arange(10,0,-1))

[10  9  8  7  6  5  4  3  2  1]


#### np.linspace

In [135]:
# start at 1 and end at 50
np.linspace(start=1,stop=50,num=10, dtype=int)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

In [136]:
# limit the number of digits after the decimal to 2
np.set_printoptions(precision=2)

#start at 10^1 and end at 10^50
np.logspace(start=1, stop=50, num=10, base=10)

array([1.00e+01, 2.78e+06, 7.74e+11, 2.15e+17, 5.99e+22, 1.67e+28,
       4.64e+33, 1.29e+39, 3.59e+44, 1.00e+50])

##### np.zero and np.ones

functions lets you create arrays of desired shape where all the items are either 0’s or 1’s.


In [137]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [138]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

## How to create repeating sequences
np.tile(x,n) | np.repeat(x,n)

In [139]:
a = [1, 2, 3]

#### np.tile(x,n)

In [140]:
# repeat whole of 'a' two times
print('Title: ', np.tile(a,2))

Title:  [1 2 3 1 2 3]


np.repeat(x,n)

In [141]:
# repeat each element of 'a' two times
print('Repeat: ', np.repeat(a,2))

Repeat:  [1 1 2 2 3 3]


### How to generate random numbers

np.random

In [142]:
# random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

[[0.21 0.45]
 [0.87 0.06]]


In [143]:
# normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randn(2,2))

[[ 0.43  2.3 ]
 [-0.12  0.02]]


In [144]:
# random integers between [0,10) of shape 2,2
print(np.random.randint(0, 10, size=[2,2]))

[[2 4]
 [1 5]]


In [145]:
# one random number between [0,1)
print(np.random.random(size=[2,2]))

[[0.31 0.63]
 [0.7  0.64]]


In [146]:
# pick 10 itens from a given list, with equal probability
print(np.random.choice(['a','e','i','o','u'], size=10))

['e' 'o' 'a' 'i' 'e' 'e' 'o' 'i' 'o' 'a']


In [147]:
# Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1]))  # picks more o's

['e' 'i' 'i' 'i' 'a' 'o' 'o' 'e' 'o' 'u']


## How to get the unique items and the counts
np.unique

In [148]:
# Create random integers of size 10 between [0,10)
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
print(arr_rand)

[8 8 3 7 7 0 4 2 5 2]


In [149]:
# Get the unique items and their counts
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

Unique items :  [0 2 3 4 5 7 8]
Counts       :  [1 2 1 1 1 2 2]
